HOST = "irc.twitch.tv"
PORT = 6667
NICK = ""  # Name of the bot (all lowercase)
PASS = ""  # oAuth token
CHAN = ""  # Channel to join
WHOST = "199.9.253.119"
WCHAN = "pospywhisper"
RATE = (20/30)  # Messages per second
PATT = []  # Pattern to search for bad words should it be required
